add create and get tests
meateam/permission-service pull request #22
Opened 2021-01-14 11:10 UTC by yosef32

2021-02-01 12:08 UTC, Shahar-Y requested changes

2021-02-01 12:08 UTC, Shahar-Y commented on service/permission_test.go
> +				t.Fatalf("DownloadService.Download() error = %v, wantErr %v", err, tt.wantErr)
DownloadService?

2021-02-01 12:08 UTC, Shahar-Y commented on service/permission_test.go
> +		tt := tt
?

2021-02-13 18:39 UTC, yosef32 commented on service/permission_test.go
> +		tt := tt
this is the format on all tests in go

2021-02-13 18:47 UTC, yosef32 commented on service/permission_test.go
> +				t.Fatalf("DownloadService.Download() error = %v, wantErr %v", err, tt.wantErr)
done

2021-02-14 14:21 UTC, merged