Feature/Get permission by mongoID
meateam/permission-service pull request #9
Opened 2020-09-22 13:06 UTC by nogahaskal

2020-09-22 15:38 UTC, Shahar-Y requested changes
Looks good :+1:

2020-09-22 15:38 UTC, Shahar-Y commented on service/mongodb/store.go
> +// MongoStore holds the mongodb database and implements Store .interface
?

2020-09-23 08:04 UTC, nogahaskal commented on service/mongodb/store.go
> +// MongoStore holds the mongodb database and implements Store .interface
oops

2020-09-29 12:43 UTC, Shahar-Y approved these changes

2020-10-12 13:59 UTC, merged